### ISSUE TITLE
Not possible to set a custom aria-label for elements

### ISSUE THREAD

**Issue by dimazuien** [fkhadra/react-toastify#1164]
**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current behavior?**
<img width="657" alt="screenshot" src="https://github.com/user-attachments/assets/feedb12d-6e94-47c0-aced-c3fccb319713">
Currently, close button and progress bar (and probablly other elements) have aria-labels that can't be replaced with current API. I see that it's possible to set a custom close button and add a label there but I couldn't find anything for a progress bar. The reason I need it is internationalization, I'd like to add non-english labels for it.

**What is the expected behavior?**
1. An additional option for CommonOptions that accepts label map for aria-labels and any other text content (more prefferred),
2. An ability to customize a progress bar the same way as a close button so a different label could be added.

**Comment by fkhadra** [comment]
Hey, I've released a new major version, please read the release note before upgrading  🙏🏽 . You can now specify aria-label for a toast and there is  also keyboard navigation.

**Comment by dimazuien** [comment]
Hi, great release, thank you!

But it doesn't solve my issue unfortunately 😅. The `ariaLabel` prop adds a custom label to the element with the `Toastify__toast` class. What I'd like is a custom aria label for elements with `Toastify__close-button` and `Toastify__progress-bar` classes, both have labels "close" and "notification timer" by default and that still can't be changed 😔.
