### ISSUE TITLE
Use completely custom toast instead of overwriting classes etc.

### ISSUE THREAD

**Issue by agcty** [fkhadra/react-toastify#455]
I'd really like to use my own completely styled toast component and just use the toastify api to display/close it. It doesn't seem like this is possible (didn't find anything in the docs), is there a way to do it?

**Comment by fkhadra** [comment]
For the moment the only way is to write your own css. But with the v6 coming soon https://github.com/fkhadra/react-toastify/pull/432 this will be possible

**Comment by agcty** [comment]
Ah wow, that's good to know, thank you!

**Comment by itayganor** [comment]
100% Agree. Overwriting everything is a huge mess.
@fkhadra How does v6 solve this?

**Comment by fkhadra** [comment]
You don't have to overwrite everything. Just build yours from scratch.

```jsx
import 'react-toastify/dist/ReactToastify.minimal.css';
```

Build yours:

```css
/** Used to define container behavior: width, position: fixed etc... **/
.Toastify__toast-container {
}

/** Used to define the position of the ToastContainer **/
.Toastify__toast-container--top-left {
}
.Toastify__toast-container--top-center {
}
.Toastify__toast-container--top-right {
}
.Toastify__toast-container--bottom-left {
}
.Toastify__toast-container--bottom-center {
}
.Toastify__toast-container--bottom-right {
}

/** Classes for the displayed toast **/
.Toastify__toast {
}
.Toastify__toast--rtl {
}
.Toastify__toast--dark {
}
.Toastify__toast--default {
}
.Toastify__toast--info {
}
.Toastify__toast--success {
}
.Toastify__toast--warning {
}
.Toastify__toast--error {
}
.Toastify__toast-body {
}

/** Classes for the close button. Better use your own closeButton **/
.Toastify__close-button {
}
.Toastify__close-button--default {
}
.Toastify__close-button > svg {
}
.Toastify__close-button:hover, .Toastify__close-button:focus {
}

/** Classes for the progress bar **/
.Toastify__progress-bar {
}
.Toastify__progress-bar--animated {
}
.Toastify__progress-bar--controlled {
}
.Toastify__progress-bar--rtl {
}
.Toastify__progress-bar--default {
}
.Toastify__progress-bar--dark {
}
```

You also have an example here
[![Edit react-styled-components-toastify transition issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-styled-components-toastify-transition-issue-b9hon?fontsize=14&hidenavigation=1&theme=dark)

If you are comfortable with sass.
Grab the [scss directory](https://github.com/fkhadra/react-toastify/tree/master/scss) of the repository and build your own stylesheet. If you just want to changes some colors most of them are defined inside the `_variables.scss` file.

```
scss
├── _closeButton.scss
├── _progressBar.scss
├── _toast.scss
├── _toastContainer.scss
├── _variables.scss
├── 📁 animations
│  ├── _bounce.scss
│  ├── _flip.scss
│  ├── _slide.scss
│  └── _zoom.scss
├── main.scss
└── minimal.scss
```

Hope this can help

**Comment by hrytskivr** [comment]
It's already 6.0.2 and I can't see the ability to swap toast component for custom one, am I missing something?

**Comment by fkhadra** [comment]
Hello @hrytskivr,

2 new hooks are expose `useToast` and `useToastContainer`. Unfortunatelly this is not documented yet how to use them. I'm still thinking about the usability

**Comment by nihalanisumit** [comment]
I have created my own custom toast @hrytskivr @agcty 
![image](https://user-images.githubusercontent.com/17086105/82768867-38c10400-9e4f-11ea-92ce-2d43748e408a.png)
But auto close is not working.

**Comment by fkhadra** [comment]
Hey @nihalanisumit, looks awesome, do you mind sharing the source if possible ?

**Comment by pavelspichonak** [comment]
@fkhadra as far as I understand you are the maintainer. Yeah I know that it is not documented yet but it is implemented already and can be used and the API will not be changed? Thanks.

**Comment by fkhadra** [comment]
@pavelspichonak indeed I'm the maintainer and the author of the library. It's not documented yet cause I need to find time to do it. I don't expect the API to change that much, I would prefer to simplify it a bit.

If you are interested you can check how [ToastContainer](https://github.com/fkhadra/react-toastify/blob/master/src/components/ToastContainer.tsx) and [Toast](https://github.com/fkhadra/react-toastify/blob/master/src/components/Toast.tsx) component are implemented.

**Comment by nihalanisumit** [comment]
Toast.tsx
```
import React from 'react'
import styles from './toast.module.css'
import successIcon from './images/greentick.svg'
import errorIcon from './images/redalert.svg'
import closeIcon from './images/closebutton.svg'
export declare type ToastType = 'info' | 'success' | 'error'

interface Props {
  message: string
  type: ToastType
}

const Toast: React.SFC<Props> = (props) => {
  return (
    <div
      className={styles.container}
      style={{ borderColor: props.type === 'success' ? '#27AE60' : '#EB5757' }}
    >
      <div className={styles.flex}>
        <div>
          <img src={props.type === 'success' ? successIcon : errorIcon} />
        </div>
        <p className={styles.message}>{props.message}</p>
        <div className={styles.closeButton}>
          <img src={closeIcon} />{' '}
        </div>
      </div>
    </div>
  )
}

export default Toast
```
**toast.module.css**
```
.container {
  padding: 20px 16px;
  background: #333;
  width: 100%;
  border-left: solid 4px #27ae60;
}

.flex {
  display: flex;
  flex-direction: row;
  justify-content: flex-start;
  align-items: center;
  font-size: 16px;
  font-family: Open Sans;
}

.message {
  padding: 0px 16px;
  margin: 0px;
  color: #fff;
}

.closeButton {
  margin-left: auto;
}
```
In **app.css**
```
.Toastify__toast {
  border-radius: 4px;
  background-color: #333;
  padding: 0px;
}

.Toastify__toast-container {
  width: min(400px, 100vw);
}
```

Finally,
```
import React from 'react'
import { toast, ToastOptions, Slide } from 'react-toastify'
import ToastUI, { ToastType } from './Toast'

const toastOptions: ToastOptions = {
  position: 'top-center',
  autoClose: 10000,
  hideProgressBar: true,
  closeOnClick: true,
  pauseOnHover: true,
  draggable: true,
  progress: undefined,
  transition: Slide,
  rtl: false,
  closeButton: false,
}

export const sendNotification = (message: string, type: ToastType) => {
  toast(<ToastUI message={message} type={type} />, toastOptions)
}
```

cc @fkhadra

**Comment by stoplion** [comment]
This example is not working for me. :(

**Comment by Delta-official** [comment]
@nihalanisumit 

This is really interesting, but for some reason the toast is displaying incorrectly for me (I made some small modifications so it looked like I needed, but the strange margin/padding on the toast couldn't be removed)
![Знімок екрана  о 21 35 11](https://user-images.githubusercontent.com/64544951/117549863-73628300-b045-11eb-8486-2ca289050e42.png)

**Comment by PukarHub** [comment]
@fkhadra  hey , I just wanted to change the background color for all the toast that are available, I am using scss , react-typescript and I have parcel bundler too. I tried all the possible way from your documentation to change the background but it's not working can you help me out. @fkhadra

**Comment by fkhadra** [comment]
Hey @PukarHub sorry for the late reply. I've released a new major version that allows more configuration when it comes to styling. https://fkhadra.github.io/react-toastify/migration-v8

**Comment by PukarHub** [comment]
Hey there , It is still not working on my application. Can you help me
please??

**Comment by mthaak** [comment]
Another way of doing this (and I suspect @fkhadra's intention) is to create your own implementation of `ToastContainer` and `Toast` by using the `useToastContainer` and `useToast` hooks. This implementation can take inspiration from the existing [ToastContainer.tsx](https://github.com/fkhadra/react-toastify/blob/master/src/components/ToastContainer.tsx) and [Toast.tsx](https://github.com/fkhadra/react-toastify/blob/master/src/components/Toast.tsx) but instead of rendering plain `divs` in `Toast.tsx` you render your own custom toast.

This is how I plugged the `ToastNotification` from the Carbon Design System into react-toastify:
[Toast.tsx](https://gist.github.com/mthaak/ac8af43f2c9a83ae960a38dd00e0d6b6)
[ToastContainer.tsx](https://gist.github.com/mthaak/d98e9cb45cf687d9a99c512a485d18e1)
[toast.ts](https://gist.github.com/mthaak/83418c4fd4a6703dac129ea4c0dd7fc5)
[Toast.module.scss](https://gist.github.com/mthaak/557afee4bfcdd3011aee6d0b4690bf20)
[toastUtils.ts](https://gist.github.com/mthaak/652f318ce9baf2bb19ee2876c931ca25)

I created a new `toast` function that takes a `title`, `subtitle` and `caption` a renders a Carbon Toast notification like so:
```javascript
toast("My title", "My subtitle", "My caption")
```
![image](https://user-images.githubusercontent.com/6129322/180420375-ad947b04-3270-4198-bac7-9e5cf9522c29.png)

This solution requires quite a lot of code though. It would be nicer if the react-toastify's `ToastContainer` component could take a custom `Toast` component to render. E.g. `customToast: (props: ToastProps) => ReactNode` @fkhadra

**Comment by Faithfinder** [comment]
Since you're allowed to render a React component as a prop you can just wrap library's methods, like this, I believe. Ideally there would be no extra wrapper divs from library, but you can neutralize them easily enough. Other than that, I believe ergonomics are quite tolerable.

```ts

type MyToastProps = {
  title: string
  description: string
  timestamp: string
}

export const showToast = (myProps: MyToastProps, options: ToastOptions) => {
   return toast(<MyToastImplementation {...myProps} />, options);
}

export const updateToast = (id: string | number, myProps: MyToastProps, options: ToastOptions) => {
   return toast.update(id, {
        render: <MyToastImplementation {...myProps} />,
        ...options
    });
}

**Comment by keithburgie** [comment]
If anyone happens to come along who still has this question, this is how I created a custom toast without losing placement or animation:

Note that this is importing the standard stylesheet and not `ReactToastify.minimal.css`.
```tsx
// index.tsx
import * as React from "react";
import ReactDOM from "react-dom";
import { ToastContainer } from "react-toastify";
import { App } from "app";

import "react-toastify/dist/ReactToastify.css";
import "styles/toastify.css";
import "styles/index.css";

ReactDOM.render(
  <React.StrictMode>
    <App />
    <ToastContainer
      hideProgressBar={true}
      closeButton={false}
      draggable={false}
      position="top-right"
      autoClose={5000}
      />
  </React.StrictMode>,
  document.getElementById('root')
);
```

Create a custom stylesheet for overrides:
```css
:root {
  --toast-y-position: 1.25rem;
  --toast-x-position: 2rem;
}

.Toastify__toast-container {
  width: auto;
  padding: 0;
}

.Toastify__toast-container--top-left {
  top: var(--toast-y-position);
  left: var(--toast-x-position);
}

.Toastify__toast-container--top-center {
  top: var(--toast-y-position);
  left: 50%;
  transform: translateX(-50%);
}

.Toastify__toast-container--top-right {
  top: var(--toast-y-position);
  right: var(--toast-x-position);
}

.Toastify__toast-container--bottom-left {
  bottom: var(--toast-y-position);
  left: var(--toast-x-position);
}

.Toastify__toast-container--bottom-center {
  bottom: var(--toast-y-position);
  left: 50%;
  transform: translateX(-50%);
}

.Toastify__toast-container--bottom-right {
  bottom: var(--toast-y-position);
  right: var(--toast-x-position);
}

.Toastify__toast {
  background: none;
  border-radius: 0;
  box-shadow: none;
  color: inherit;
  min-height: unset;
  overflow: unset;
  padding: 0;
}

.Toastify__toast-body {
  padding: 0;
}

.Toastify__progress-bar {
  display: none;
}
```

Create your custom component:
```tsx
const MyCustomToast = () => {
  return (
    <div className={toastClassNames} role="alert">
      <div className="inline-flex items-center justify-center self-baseline flex-shrink-0">
        <IconComponent className="size-6" role="img" aria-label={iconLabel} />
      </div>
      <div className="px-4 space-y-1 leading-6">
        {title && <div className="font-bold">{title}</div>}
        {message && <div className="font-normal">{message}</div>}
      </div>
      <CloseButton onClick={onClose} aria-label="Close Notification" />
    </div>
  );
}
```

Use it in your app:
```tsx
import { toast } from "react-toastify";
....
() => toast(
  <MyCustomToast
    status="success"
    title="Woohoo"
    message="We did the thing!"
  />,{
    // any unique toast options
  }
);
```

**Comment by PukarHub** [comment]
Hey Mate,

Thankyou so much for sharing this to me . Really appreciate it.

Have a great day .

Best Regards,
Pukar

**Comment by fkhadra** [comment]
Hello, the v11 is launching soon, I'm currently updating the documentation. Customizing the notifications is now super straightforward so the library can be used in any design system.

![Screenshot 2024-12-11 at 10 26 23](https://github.com/user-attachments/assets/0a6d0c4e-208a-4705-afd2-b26ac4666bf3)

https://stackblitz.com/edit/react-toastify-how-to-style?file=src%2FApp.tsx
