### ISSUE TITLE
toast.promise stuck on pending when promise completes before toast initializes

### ISSUE THREAD

**Issue by CCCS-NoahS** [fkhadra/react-toastify#932]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When a page is first loaded, if a promise is fulfilled within a `useEffect(..., [ ])` before the toast notification can display, the toast will be stuck on pending with no way to update. Furthermore, it can't be closed, and it doesn't timeout since it is loading.
I have also tested it by manually creating the toast using toast.loading, and calling toast.update in the promise callback.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

Currently unable to produce in codesandbox.io, although I will attempt to update as soon as possible with a valid codesandbox.
My current steps are performing an asynchronus AXIOS REST request within an empty-dependency `useEffect(..., [ ])`. Inside of this, I use toast.promise to provide a notification on the status of the REST request. 
When the web ui is refreshsed on such a page, the toast notification is stuck on the "pending" stage. It does not occur when navigating between pages in the UI (which is why I believe it is linked to ToastContainer's initialization, which would only happen on page refresh).
Lastly, the notification also doesn't get stuck when I am debugging and have a breakpoint at any point before the original toast is created. (Even if the breakpoint is AFTER the request has been sent)

**What is the expected behavior?**

Toast should automatically start on succeeded if the promise has been completed. Furthermore, you should be able to dismiss a pending toast based on the ToastContainer parameters (potentially duplicate issue)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Affected on firefox/chrome. Most recently tested on Linux, but I've had the issue on Windows in the past as well.
 Hasn't worked in previous versions as far as I'm aware. React package version to follow.
```
├── react-dom@18.2.0
├── react-dropzone@14.2.3
├── react-i18next@11.18.6
├── react-icons@4.7.1
├── react-router-dom@6.6.2
├── react-router@6.6.2
├── react-scripts@5.0.1
├── react-toastify@9.1.1
├── react@18.2.0
```

**Comment by fkhadra** [comment]
Hey @CCCS-NoahS, I've just published a new version. I believe the issue should be fixed can you give it a try? Thanks

**Comment by CCCS-NoahS** [comment]
Still appears to be an issue with 9.1.2 (both getting stuck on pending and being unable to close)
I'm curious where you thought the fix was (wouldn't mind learning more about the project since I've enjoyed using it, and might help me test/recreate it in codesandbox)

**Comment by CCCS-NoahS** [comment]
I haven't been able to recreate the behaviour in codesandbox, but I'll at least describe some of the code I am using here.
I do definte it alongside the last step of the rendering, after everything is set up (in particular so the theme is defined in my case). I did try moving it with a static theme higher in the initialization priority, but that didn't seem to work (on 9.1.1 or 9.1.2)
`
<BrowserRouter>
      <AppProvider {...props}> 
        <AuthorizationProvider {...props}> 
              <ToastContainer autoClose={5000} position="bottom-right" theme={theme.palette.mode} closeOnClick={true} />
              <MyRoutes/>
        </AuthorizationProvider >
      </AppProvider>
    </BrowserRouter>
`
Not sure if that helps contextualize things at all, but I can't be anymore specific about how the app works/is set up.
I've also tried moving the toastcontainer (without any props) to every individual level of the app. Including up to the highest level and also down within the actual component itself. Not sure if theres anything in the actual ToastContainer code I could look ot debug and potentially use

**Comment by CCCS-NoahS** [comment]
Ah shit, I'm just being an idiot. Although not something I noticed in the docs

Checked and we were using the outdated ReactDOM.render. Switching to createRoot (so the app ACTUALLY behaves like react 18) has fixed the issue.

see https://github.com/reactwg/react-18/discussions/5
